/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.metodosdeestudio;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.sound.sampled.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Juan Lopera
 */
public class Alarma extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    public Alarma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Label3 = new javax.swing.JLabel();
        b_volver = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        b_guardar2 = new javax.swing.JButton();
        nota1content = new javax.swing.JLabel();
        nota2content = new javax.swing.JLabel();
        nota3content = new javax.swing.JLabel();
        nota4content = new javax.swing.JLabel();
        nota5content = new javax.swing.JLabel();
        nota1title = new javax.swing.JLabel();
        nota2title = new javax.swing.JLabel();
        nota3title = new javax.swing.JLabel();
        nota4title = new javax.swing.JLabel();
        nota5title = new javax.swing.JLabel();
        tema = new javax.swing.JLabel();
        comingfrom = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        s_horas = new javax.swing.JSpinner();
        s_minutos = new javax.swing.JSpinner();
        s_segundos = new javax.swing.JSpinner();
        tone = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        Label3.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        Label3.setText("MINUTOS");

        b_volver.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        b_volver.setText("VOLVER");
        b_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        Label1.setText("ALARMA");

        Label2.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        Label2.setText("HORAS");

        b_guardar2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        b_guardar2.setText("GUARDAR");
        b_guardar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_guardar2.setMaximumSize(new java.awt.Dimension(100, 25));
        b_guardar2.setMinimumSize(new java.awt.Dimension(100, 25));
        b_guardar2.setPreferredSize(new java.awt.Dimension(100, 25));
        b_guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    b_guardar2ActionPerformed(evt);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(Alarma.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Alarma.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(Alarma.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        nota1content.setText("jLabel1");
        nota1content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota1content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota1content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota2content.setText("jLabel1");
        nota2content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota2content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota2content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota3content.setText("jLabel1");
        nota3content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota3content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota3content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota4content.setText("jLabel1");
        nota4content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota4content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota4content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota5content.setText("jLabel1");
        nota5content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota5content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota5content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota1title.setText("jLabel1");
        nota1title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota1title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota1title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota2title.setText("jLabel1");
        nota2title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota2title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota2title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota3title.setText("jLabel1");
        nota3title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota3title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota3title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota4title.setText("jLabel1");
        nota4title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota4title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota4title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota5title.setText("jLabel1");
        nota5title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota5title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota5title.setPreferredSize(new java.awt.Dimension(0, 0));

        tema.setText("jLabel1");
        tema.setMaximumSize(new java.awt.Dimension(0, 0));
        tema.setMinimumSize(new java.awt.Dimension(0, 0));
        tema.setPreferredSize(new java.awt.Dimension(0, 0));

        Label4.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        Label4.setText("SEGUNDOS");

        s_horas.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        s_horas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        s_minutos.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        s_minutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        s_segundos.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        s_segundos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tone.setText("jLabel1");
        tone.setMaximumSize(new java.awt.Dimension(0, 0));
        tone.setMinimumSize(new java.awt.Dimension(0, 0));
        tone.setPreferredSize(new java.awt.Dimension(0, 0));

        Label5.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        Label5.setText("Las alarmas son cruciales para el método de estudio Pomodoro, marcando sesiones de 25 minutos");

        Label6.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        Label6.setText("de concentración y descansos de 5 minutos, optimizando la productividad estudiantil.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b_volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(Label1)))
                .addGap(57, 429, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(s_horas)
                    .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_guardar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(202, 202, 202)
                        .addComponent(Label4)
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(s_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(s_segundos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label6)
                    .addComponent(Label5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(522, Short.MAX_VALUE)
                    .addComponent(tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(502, 502, 502)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(512, 512, 512)
                    .addComponent(comingfrom)
                    .addContainerGap(512, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(512, 512, 512)
                    .addComponent(tone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(512, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(b_volver)
                .addGap(34, 34, 34)
                .addComponent(Label1)
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label2)
                    .addComponent(Label3)
                    .addComponent(Label4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_horas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_segundos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173)
                .addComponent(b_guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(Label5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label6)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(394, Short.MAX_VALUE)
                    .addComponent(tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(374, 374, 374)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(384, 384, 384)
                    .addComponent(comingfrom)
                    .addContainerGap(384, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(384, 384, 384)
                    .addComponent(tone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(384, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold> 
    
    /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Label3 = new javax.swing.JLabel();
        b_volver = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        b_guardar2 = new javax.swing.JButton();
        nota1content = new javax.swing.JLabel();
        nota2content = new javax.swing.JLabel();
        nota3content = new javax.swing.JLabel();
        nota4content = new javax.swing.JLabel();
        nota5content = new javax.swing.JLabel();
        nota1title = new javax.swing.JLabel();
        nota2title = new javax.swing.JLabel();
        nota3title = new javax.swing.JLabel();
        nota4title = new javax.swing.JLabel();
        nota5title = new javax.swing.JLabel();
        tema = new javax.swing.JLabel();
        comingfrom = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        s_horas = new javax.swing.JSpinner();
        s_minutos = new javax.swing.JSpinner();
        s_segundos = new javax.swing.JSpinner();
        tone = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        Label3.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        Label3.setText("MINUTOS");

        b_volver.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        b_volver.setText("VOLVER");
        b_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        Label1.setText("ALARMA");

        Label2.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        Label2.setText("HORAS");

        b_guardar2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        b_guardar2.setText("GUARDAR");
        b_guardar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_guardar2.setMaximumSize(new java.awt.Dimension(100, 25));
        b_guardar2.setMinimumSize(new java.awt.Dimension(100, 25));
        b_guardar2.setPreferredSize(new java.awt.Dimension(100, 25));
        b_guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardar2ActionPerformed(evt);
            }
        });

        nota1content.setText("jLabel1");
        nota1content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota1content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota1content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota2content.setText("jLabel1");
        nota2content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota2content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota2content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota3content.setText("jLabel1");
        nota3content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota3content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota3content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota4content.setText("jLabel1");
        nota4content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota4content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota4content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota5content.setText("jLabel1");
        nota5content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota5content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota5content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota1title.setText("jLabel1");
        nota1title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota1title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota1title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota2title.setText("jLabel1");
        nota2title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota2title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota2title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota3title.setText("jLabel1");
        nota3title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota3title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota3title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota4title.setText("jLabel1");
        nota4title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota4title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota4title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota5title.setText("jLabel1");
        nota5title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota5title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota5title.setPreferredSize(new java.awt.Dimension(0, 0));

        tema.setText("jLabel1");
        tema.setMaximumSize(new java.awt.Dimension(0, 0));
        tema.setMinimumSize(new java.awt.Dimension(0, 0));
        tema.setPreferredSize(new java.awt.Dimension(0, 0));

        Label4.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        Label4.setText("SEGUNDOS");

        s_horas.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        s_horas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        s_minutos.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        s_minutos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        s_segundos.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        s_segundos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tone.setText("jLabel1");
        tone.setMaximumSize(new java.awt.Dimension(0, 0));
        tone.setMinimumSize(new java.awt.Dimension(0, 0));
        tone.setPreferredSize(new java.awt.Dimension(0, 0));

        Label5.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        Label5.setText("Las alarmas son cruciales para el método de estudio Pomodoro, marcando sesiones de 25 minutos");

        Label6.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        Label6.setText("de concentración y descansos de 5 minutos, optimizando la productividad estudiantil.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b_volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(Label1)))
                .addGap(57, 429, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(s_horas)
                    .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_guardar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(202, 202, 202)
                        .addComponent(Label4)
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(s_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(s_segundos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label6)
                    .addComponent(Label5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(522, Short.MAX_VALUE)
                    .addComponent(tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(502, 502, 502)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(512, 512, 512)
                    .addComponent(comingfrom)
                    .addContainerGap(512, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(512, 512, 512)
                    .addComponent(tone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(512, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(b_volver)
                .addGap(34, 34, 34)
                .addComponent(Label1)
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label2)
                    .addComponent(Label3)
                    .addComponent(Label4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_horas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_segundos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173)
                .addComponent(b_guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(Label5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label6)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(394, Short.MAX_VALUE)
                    .addComponent(tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(374, 374, 374)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(384, 384, 384)
                    .addComponent(comingfrom)
                    .addContainerGap(384, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(384, 384, 384)
                    .addComponent(tone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(384, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    */
    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        String come = comingfrom.getText();
        if (come.equals("visual")) {
            //VISUAL
            Visual audi = new Visual();
            
            //SEND NOTES
            audi.nota1content.setText(this.nota1content.getText());
            audi.nota2content.setText(this.nota2content.getText());
            audi.nota3content.setText(this.nota3content.getText());
            audi.nota4content.setText(this.nota4content.getText());
            audi.nota5content.setText(this.nota5content.getText());

            audi.nota1title.setText(this.nota1title.getText());
            audi.nota2title.setText(this.nota2title.getText());
            audi.nota3title.setText(this.nota3title.getText());
            audi.nota4title.setText(this.nota4title.getText());
            audi.nota5title.setText(this.nota5title.getText());
            //SEND NOTES END
            
            //SEND THEME AND TONE
            audi.tema.setText(this.tema.getText());
            audi.tone.setText(this.tone.getText());
            
            if (tema.getText().equals("clara")) {
                Color MyColor = new Color(235,235,235);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.BLACK);
            } else if (tema.getText().equals("oscura")) {
                Color MyColor = new Color(34,39,44);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            } else if (tema.getText().equals("morada")) {
                Color MyColor = new Color(128, 0, 128);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            } else if (tema.getText().equals("azul")) {
                Color MyColor = new Color(85,137,249);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            }
            
            //SEND THEME AND TONE END
            
            //SEND TASKS
            audi.size = size;
            audi.jlistdata = new String[audi.size];
            if (size != 0) {
               for (int i = 0; i<audi.size; i++) {
                audi.jlistdata[i] = jlistdata[i];
            }
            }
        //END SEND TASKS
            audi.show();
            dispose();
        } else if (come.equals("auditivo")) {
            //AUDITIVO
            Auditivo audi = new Auditivo();
            
            //SEND NOTES
            audi.nota1content.setText(this.nota1content.getText());
            audi.nota2content.setText(this.nota2content.getText());
            audi.nota3content.setText(this.nota3content.getText());
            audi.nota4content.setText(this.nota4content.getText());
            audi.nota5content.setText(this.nota5content.getText());

            audi.nota1title.setText(this.nota1title.getText());
            audi.nota2title.setText(this.nota2title.getText());
            audi.nota3title.setText(this.nota3title.getText());
            audi.nota4title.setText(this.nota4title.getText());
            audi.nota5title.setText(this.nota5title.getText());
            //SEND NOTES END
            
            //SEND THEME AND TONE
            audi.tema.setText(this.tema.getText());
            audi.tone.setText(this.tone.getText());
            
            if (tema.getText().equals("clara")) {
                Color MyColor = new Color(235,235,235);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.BLACK);
            } else if (tema.getText().equals("oscura")) {
                Color MyColor = new Color(34,39,44);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            } else if (tema.getText().equals("morada")) {
                Color MyColor = new Color(128, 0, 128);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            } else if (tema.getText().equals("azul")) {
                Color MyColor = new Color(85,137,249);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            }
            
            //SEND THEME AND TONE END
            
            //SEND TASKS
            audi.size = size;
            audi.jlistdata = new String[audi.size];
            if (size != 0) {
               for (int i = 0; i<audi.size; i++) {
                audi.jlistdata[i] = jlistdata[i];
            }
            }
        //END SEND TASKS
            audi.show();
            dispose();
        } else if (come.equals("kinestesico")) {
            //KINESTESICO
            Kinestesico audi = new Kinestesico();
            
            //SEND NOTES
            audi.nota1content.setText(this.nota1content.getText());
            audi.nota2content.setText(this.nota2content.getText());
            audi.nota3content.setText(this.nota3content.getText());
            audi.nota4content.setText(this.nota4content.getText());
            audi.nota5content.setText(this.nota5content.getText());

            audi.nota1title.setText(this.nota1title.getText());
            audi.nota2title.setText(this.nota2title.getText());
            audi.nota3title.setText(this.nota3title.getText());
            audi.nota4title.setText(this.nota4title.getText());
            audi.nota5title.setText(this.nota5title.getText());
            //SEND NOTES END
            
            //SEND THEME AND TONE
            audi.tema.setText(this.tema.getText());
            audi.tone.setText(this.tone.getText());
            
            if (tema.getText().equals("clara")) {
                Color MyColor = new Color(235,235,235);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.BLACK);
            } else if (tema.getText().equals("oscura")) {
                Color MyColor = new Color(34,39,44);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            } else if (tema.getText().equals("morada")) {
                Color MyColor = new Color(128, 0, 128);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            } else if (tema.getText().equals("azul")) {
                Color MyColor = new Color(85,137,249);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            }
            
            //SEND THEME AND TONE END
            
            //SEND TASKS
            audi.size = size;
            audi.jlistdata = new String[audi.size];
            if (size != 0) {
               for (int i = 0; i<audi.size; i++) {
                audi.jlistdata[i] = jlistdata[i];
            }
            }
        //END SEND TASKS
            audi.show();
            dispose();
        }
    }//GEN-LAST:event_b_volverActionPerformed
    /*
    private void b_guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_guardar2ActionPerformed
    */
    
    private void b_guardar2ActionPerformed(java.awt.event.ActionEvent evt) throws UnsupportedAudioFileException, IOException, LineUnavailableException {                                           
        int hour = (Integer) s_horas.getValue();
        int minute = (Integer) s_minutos.getValue();
        int second = (Integer) s_segundos.getValue();
        File alarmsound = new File("tone1.wav");
        if (tone.getText().equals("tone1")) {
            alarmsound = new File("tone1.wav");
        } else if (tone.getText().equals("tone2")) {
            alarmsound = new File("tone2.wav");
        } else if (tone.getText().equals("tone3")) {
            alarmsound = new File("tone3.wav");
        } else if (tone.getText().equals("tone4")) {
            alarmsound = new File("tone4.wav");
        }
        AudioInputStream audioStream = AudioSystem.getAudioInputStream(alarmsound);
        Clip clip = AudioSystem.getClip();
        clip.open(audioStream);
        Timer alert = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                clip.start();
            }
        };
        int delay = second*1000 + minute*1000*60 + hour*1000*60*60;
        alert.schedule(task,delay);
    }
    
    public void changetext(Color a) {
        Label1.setForeground(a);
        Label2.setForeground(a);
        Label3.setForeground(a);
        Label4.setForeground(a);
        Label5.setForeground(a);
        Label6.setForeground(a);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alarma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alarma().setVisible(true);
                
            }
        });
    }

    public int size = 0;
    public String[] jlistdata;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JButton b_guardar2;
    private javax.swing.JButton b_volver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JLabel comingfrom;
    public javax.swing.JLabel nota1content;
    public javax.swing.JLabel nota1title;
    public javax.swing.JLabel nota2content;
    public javax.swing.JLabel nota2title;
    public javax.swing.JLabel nota3content;
    public javax.swing.JLabel nota3title;
    public javax.swing.JLabel nota4content;
    public javax.swing.JLabel nota4title;
    public javax.swing.JLabel nota5content;
    public javax.swing.JLabel nota5title;
    private javax.swing.JSpinner s_horas;
    private javax.swing.JSpinner s_minutos;
    private javax.swing.JSpinner s_segundos;
    public javax.swing.JLabel tema;
    public javax.swing.JLabel tone;
    // End of variables declaration//GEN-END:variables
}
