/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.metodosdeestudio;

import java.awt.Color;

/**
 *
 * @author Juan Lopera
 */
public class VisualTips extends javax.swing.JFrame {

    /**
     * Creates new form Auditivo
     */
    public VisualTips() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label1 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        b_volver = new javax.swing.JButton();
        b_configuracion = new javax.swing.JButton();
        b_notas = new javax.swing.JButton();
        b_tareas = new javax.swing.JButton();
        b_alarma = new javax.swing.JButton();
        Label2 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Label13 = new javax.swing.JLabel();
        nota1content = new javax.swing.JLabel();
        nota2content = new javax.swing.JLabel();
        nota3content = new javax.swing.JLabel();
        nota4content = new javax.swing.JLabel();
        nota5content = new javax.swing.JLabel();
        nota1title = new javax.swing.JLabel();
        nota2title = new javax.swing.JLabel();
        nota3title = new javax.swing.JLabel();
        nota4title = new javax.swing.JLabel();
        nota5title = new javax.swing.JLabel();
        tema = new javax.swing.JLabel();
        tone = new javax.swing.JLabel();
        Label14 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("metodoauditivo"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        Label1.setFont(new java.awt.Font("Sitka Small", 1, 36)); // NOI18N
        Label1.setText("METODO VISUAL");

        Label3.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label3.setText("1. Toma muchos apuntes, esto te ayudara a recordar las cosas mas fácilmente.");

        Label4.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label4.setText("2. Asegúrate de que tu zona de estudio este muy bien organizada.");

        Label6.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label6.setText("3. Mira a las personas y a los profesores cuando te están explicando algo, esto te ayudara a mantener tu atención en el tema.");

        Label7.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label7.setText("4. Intenta estudiar por tu cuenta, la mayoría de personas que aprenden mejor visualmente tienen mejores resultados con estudio");

        Label8.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label8.setText("5. Revisa todas tus notas justo después de clase o de que te hayan explicado un concepto, esto se debe a que tu cerebro todavía puede");

        b_volver.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        b_volver.setText("VOLVER");
        b_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });

        b_configuracion.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        b_configuracion.setText("CONFIGURACION");
        b_configuracion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_configuracion.setMaximumSize(new java.awt.Dimension(134, 23));
        b_configuracion.setPreferredSize(new java.awt.Dimension(134, 23));
        b_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_configuracionActionPerformed(evt);
            }
        });

        b_notas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        b_notas.setText("NOTAS");
        b_notas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_notas.setMaximumSize(new java.awt.Dimension(134, 23));
        b_notas.setPreferredSize(new java.awt.Dimension(134, 23));
        b_notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_notasActionPerformed(evt);
            }
        });

        b_tareas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        b_tareas.setText("TAREAS");
        b_tareas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_tareas.setMaximumSize(new java.awt.Dimension(134, 23));
        b_tareas.setPreferredSize(new java.awt.Dimension(134, 23));
        b_tareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tareasActionPerformed(evt);
            }
        });

        b_alarma.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        b_alarma.setText("ALARMA");
        b_alarma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_alarma.setMaximumSize(new java.awt.Dimension(134, 23));
        b_alarma.setPreferredSize(new java.awt.Dimension(134, 23));
        b_alarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alarmaActionPerformed(evt);
            }
        });

        Label2.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        Label2.setText("TIPS / CONSEJOS");

        Label10.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label10.setText("recordar gran parte de la información, por lo que reforzar este conocimiento es mucho más fácil por medio de la revisión de notas.");

        Label12.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label12.setText("7. Usa resaltadores para subrayar todas las ideas importantes en un texto, asegúrate de que sea un color vibrante que capte tu atención.");

        Label11.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label11.setText("6. Intenta trabajar en intervalos de 25 minutos, es importante tomar un descanso corto después de leer o realizar alguna actividad");

        Label13.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label13.setText("8. Revisa todo el contenido resaltado luego de cada descanso corto que tomes.");

        nota1content.setText("jLabel1");
        nota1content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota1content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota1content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota2content.setText("jLabel1");
        nota2content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota2content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota2content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota3content.setText("jLabel1");
        nota3content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota3content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota3content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota4content.setText("jLabel1");
        nota4content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota4content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota4content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota5content.setText("jLabel1");
        nota5content.setMaximumSize(new java.awt.Dimension(0, 0));
        nota5content.setMinimumSize(new java.awt.Dimension(0, 0));
        nota5content.setPreferredSize(new java.awt.Dimension(0, 0));

        nota1title.setText("jLabel1");
        nota1title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota1title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota1title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota2title.setText("jLabel1");
        nota2title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota2title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota2title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota3title.setText("jLabel1");
        nota3title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota3title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota3title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota4title.setText("jLabel1");
        nota4title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota4title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota4title.setPreferredSize(new java.awt.Dimension(0, 0));

        nota5title.setText("jLabel1");
        nota5title.setMaximumSize(new java.awt.Dimension(0, 0));
        nota5title.setMinimumSize(new java.awt.Dimension(0, 0));
        nota5title.setPreferredSize(new java.awt.Dimension(0, 0));

        tema.setText("jLabel1");
        tema.setMaximumSize(new java.awt.Dimension(0, 0));
        tema.setMinimumSize(new java.awt.Dimension(0, 0));
        tema.setPreferredSize(new java.awt.Dimension(0, 0));

        tone.setText("jLabel1");
        tone.setMaximumSize(new java.awt.Dimension(0, 0));
        tone.setMinimumSize(new java.awt.Dimension(0, 0));
        tone.setPreferredSize(new java.awt.Dimension(0, 0));

        Label14.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label14.setText("académica durante este tiempo.");

        Label9.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        Label9.setText("solitario que con estudio grupal.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_volver)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_notas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_tareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_alarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label11)
                            .addComponent(Label6)
                            .addComponent(Label7)
                            .addComponent(Label8)
                            .addComponent(Label10)
                            .addComponent(Label12)
                            .addComponent(Label13)
                            .addComponent(Label3)
                            .addComponent(Label4)
                            .addComponent(Label14)
                            .addComponent(Label9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(Label2))
                            .addComponent(Label1))))
                .addContainerGap(322, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1292, 1292, 1292)
                    .addComponent(tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1292, 1292, 1292)
                    .addComponent(tone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(b_volver)
                .addGap(7, 7, 7)
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_notas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_tareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_alarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota1title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota2title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota3title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota4title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(nota5title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(348, 348, 348)
                    .addComponent(tema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(348, 348, 348)
                    .addComponent(tone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        Visual audi = new Visual();
        
        //SEND NOTES
        audi.nota1content.setText(this.nota1content.getText());
        audi.nota2content.setText(this.nota2content.getText());
        audi.nota3content.setText(this.nota3content.getText());
        audi.nota4content.setText(this.nota4content.getText());
        audi.nota5content.setText(this.nota5content.getText());
        
        audi.nota1title.setText(this.nota1title.getText());
        audi.nota2title.setText(this.nota2title.getText());
        audi.nota3title.setText(this.nota3title.getText());
        audi.nota4title.setText(this.nota4title.getText());
        audi.nota5title.setText(this.nota5title.getText());
        //SEND NOTES END
        
        //SEND THEME AND TONE
            audi.tema.setText(this.tema.getText());
            audi.tone.setText(this.tone.getText());
            
            if (tema.getText().equals("clara")) {
                Color MyColor = new Color(235,235,235);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.BLACK);
            } else if (tema.getText().equals("oscura")) {
                Color MyColor = new Color(34,39,44);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            } else if (tema.getText().equals("morada")) {
                Color MyColor = new Color(128, 0, 128);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            } else if (tema.getText().equals("azul")) {
                Color MyColor = new Color(85,137,249);
                audi.getContentPane().setBackground(MyColor);
                audi.changetext(Color.WHITE);
            }
            
            //SEND THEME AND TONE END
            
            //SEND TASKS
            audi.size = size;
            audi.jlistdata = new String[audi.size];
            if (size != 0) {
               for (int i = 0; i<audi.size; i++) {
                audi.jlistdata[i] = jlistdata[i];
            }
            }
        //END SEND TASKS
            
        audi.show();
        dispose();
    }//GEN-LAST:event_b_volverActionPerformed

    private void b_notasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_notasActionPerformed
        Notas notes = new Notas();
        //SEND NOTES
        notes.comingfrom.setText("visual");
        notes.comingfrom.setVisible(false);
        
        notes.nota1content.setText(this.nota1content.getText());
        notes.nota2content.setText(this.nota2content.getText());
        notes.nota3content.setText(this.nota3content.getText());
        notes.nota4content.setText(this.nota4content.getText());
        notes.nota5content.setText(this.nota5content.getText());
        
        notes.b_nota1.setText(this.nota1title.getText());
        notes.b_nota2.setText(this.nota2title.getText());
        notes.b_nota3.setText(this.nota3title.getText());
        notes.b_nota4.setText(this.nota4title.getText());
        notes.b_nota5.setText(this.nota5title.getText());
        //SEND NOTES END
        
        //SEND THEME AND TONE
        notes.tema.setText(this.tema.getText());
        notes.tone.setText(this.tone.getText());
        
            if (tema.getText().equals("clara")) {
                Color MyColor = new Color(235,235,235);
                notes.getContentPane().setBackground(MyColor);
                notes.changetext(Color.BLACK);
            } else if (tema.getText().equals("oscura")) {
                Color MyColor = new Color(34,39,44);
                notes.getContentPane().setBackground(MyColor);
                notes.changetext(Color.WHITE);
            } else if (tema.getText().equals("morada")) {
                Color MyColor = new Color(128, 0, 128);
                notes.getContentPane().setBackground(MyColor);
                notes.changetext(Color.WHITE);
            } else if (tema.getText().equals("azul")) {
                Color MyColor = new Color(85,137,249);
                notes.getContentPane().setBackground(MyColor);
                notes.changetext(Color.WHITE);
            }
        //SEND THEME AND TONE END
        
        //SEND TASKS
            notes.size = size;
            notes.jlistdata = new String[notes.size];
            if (size != 0) {
               for (int i = 0; i<notes.size; i++) {
                notes.jlistdata[i] = jlistdata[i];
            }
            }
        //END SEND TASKS
        
        notes.show();
        dispose();
    }//GEN-LAST:event_b_notasActionPerformed

    private void b_configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_configuracionActionPerformed
        Configuracion config = new Configuracion();
        config.comingfrom.setText("visual");
        config.comingfrom.setVisible(false);
        
        //SEND NOTES
        config.nota1content.setText(this.nota1content.getText());
        config.nota2content.setText(this.nota2content.getText());
        config.nota3content.setText(this.nota3content.getText());
        config.nota4content.setText(this.nota4content.getText());
        config.nota5content.setText(this.nota5content.getText());
        
        config.nota1title.setText(this.nota1title.getText());
        config.nota2title.setText(this.nota2title.getText());
        config.nota3title.setText(this.nota3title.getText());
        config.nota4title.setText(this.nota4title.getText());
        config.nota5title.setText(this.nota5title.getText());
        //SEND NOTES END
        
        //SEND THEME AND TONE
        config.tema.setText(this.tema.getText());
        config.tone.setText(this.tone.getText());
        
            if (tema.getText().equals("clara")) {
                Color MyColor = new Color(235,235,235);
                config.getContentPane().setBackground(MyColor);
                config.changetext(Color.BLACK);
            } else if (tema.getText().equals("oscura")) {
                Color MyColor = new Color(34,39,44);
                config.getContentPane().setBackground(MyColor);
                config.changetext(Color.WHITE);
            } else if (tema.getText().equals("morada")) {
                Color MyColor = new Color(128, 0, 128);
                config.getContentPane().setBackground(MyColor);
                config.changetext(Color.WHITE);
            } else if (tema.getText().equals("azul")) {
                Color MyColor = new Color(85,137,249);
                config.getContentPane().setBackground(MyColor);
                config.changetext(Color.WHITE);
            }
        //SEND THEME AND TONE END
        
        //SEND TASKS
            config.size = size;
            config.jlistdata = new String[config.size];
            if (size != 0) {
               for (int i = 0; i<config.size; i++) {
                config.jlistdata[i] = jlistdata[i];
            }
            }
        //END SEND TASKS
            
        config.show();
        dispose();
    }//GEN-LAST:event_b_configuracionActionPerformed

    private void b_alarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alarmaActionPerformed
         Alarma alarm = new Alarma();
        alarm.comingfrom.setText("visual");
        alarm.comingfrom.setVisible(false);
        
        //SEND NOTES
        alarm.nota1content.setText(this.nota1content.getText());
        alarm.nota2content.setText(this.nota2content.getText());
        alarm.nota3content.setText(this.nota3content.getText());
        alarm.nota4content.setText(this.nota4content.getText());
        alarm.nota5content.setText(this.nota5content.getText());
        
        alarm.nota1title.setText(this.nota1title.getText());
        alarm.nota2title.setText(this.nota2title.getText());
        alarm.nota3title.setText(this.nota3title.getText());
        alarm.nota4title.setText(this.nota4title.getText());
        alarm.nota5title.setText(this.nota5title.getText());
        //SEND NOTES END
        
        //SEND THEME AND TONE
        alarm.tema.setText(this.tema.getText());
        alarm.tone.setText(this.tone.getText());
        
            if (tema.getText().equals("clara")) {
                Color MyColor = new Color(235,235,235);
                alarm.getContentPane().setBackground(MyColor);
                alarm.changetext(Color.BLACK);
            } else if (tema.getText().equals("oscura")) {
                Color MyColor = new Color(34,39,44);
                alarm.getContentPane().setBackground(MyColor);
                alarm.changetext(Color.WHITE);
            } else if (tema.getText().equals("morada")) {
                Color MyColor = new Color(128, 0, 128);
                alarm.getContentPane().setBackground(MyColor);
                alarm.changetext(Color.WHITE);
            } else if (tema.getText().equals("azul")) {
                Color MyColor = new Color(85,137,249);
                alarm.getContentPane().setBackground(MyColor);
                alarm.changetext(Color.WHITE);
            }
        //SEND THEME AND TONE END
        
        //SEND TASKS
            alarm.size = size;
            alarm.jlistdata = new String[alarm.size];
            if (size != 0) {
               for (int i = 0; i<alarm.size; i++) {
                alarm.jlistdata[i] = jlistdata[i];
            }
            }
        //END SEND TASKS
            
        alarm.show();
        dispose();
    }//GEN-LAST:event_b_alarmaActionPerformed

    private void b_tareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tareasActionPerformed
        Tareas task = new Tareas();
        task.comingfrom.setText("visual");
        task.comingfrom.setVisible(false);
        
        //SEND NOTES
        task.nota1content.setText(this.nota1content.getText());
        task.nota2content.setText(this.nota2content.getText());
        task.nota3content.setText(this.nota3content.getText());
        task.nota4content.setText(this.nota4content.getText());
        task.nota5content.setText(this.nota5content.getText());
        
        task.nota1title.setText(this.nota1title.getText());
        task.nota2title.setText(this.nota2title.getText());
        task.nota3title.setText(this.nota3title.getText());
        task.nota4title.setText(this.nota4title.getText());
        task.nota5title.setText(this.nota5title.getText());
        //SEND NOTES END
        
        //SEND THEME AND TONE
        task.tema.setText(this.tema.getText());
        task.tone.setText(this.tone.getText());
        
            if (tema.getText().equals("clara")) {
                Color MyColor = new Color(235,235,235);
                task.getContentPane().setBackground(MyColor);
                task.changetext(Color.BLACK);
            } else if (tema.getText().equals("oscura")) {
                Color MyColor = new Color(34,39,44);
                task.getContentPane().setBackground(MyColor);
                task.changetext(Color.WHITE);
            } else if (tema.getText().equals("morada")) {
                Color MyColor = new Color(128, 0, 128);
                task.getContentPane().setBackground(MyColor);
                task.changetext(Color.WHITE);
            } else if (tema.getText().equals("azul")) {
                Color MyColor = new Color(85,137,249);
                task.getContentPane().setBackground(MyColor);
                task.changetext(Color.WHITE);
            }
        //SEND THEME AND TONE END
        
        //SEND TASKS
            task.size = size;
            task.jlistdata = new String[task.size];
            if (size != 0) {
               for (int i = 0; i<task.size; i++) {
                task.jlistdata[i] = jlistdata[i];
                
            }
            task.loadcontent();
            }
        //END SEND TASKS

        task.show();
        dispose();
    }//GEN-LAST:event_b_tareasActionPerformed

    public void changetext(Color a) {
        Label1.setForeground(a);
        Label2.setForeground(a);
        Label3.setForeground(a);
        Label4.setForeground(a);
        
        Label6.setForeground(a);
        Label7.setForeground(a);
        Label8.setForeground(a);
        
        Label10.setForeground(a);
        Label11.setForeground(a);
        Label12.setForeground(a);
        Label13.setForeground(a);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualTips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualTips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualTips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualTips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualTips().setVisible(true);
            }
        });
    }

    public int size = 0;
    public String[] jlistdata;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label13;
    private javax.swing.JLabel Label14;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JButton b_alarma;
    private javax.swing.JButton b_configuracion;
    private javax.swing.JButton b_notas;
    private javax.swing.JButton b_tareas;
    private javax.swing.JButton b_volver;
    public javax.swing.JLabel nota1content;
    public javax.swing.JLabel nota1title;
    public javax.swing.JLabel nota2content;
    public javax.swing.JLabel nota2title;
    public javax.swing.JLabel nota3content;
    public javax.swing.JLabel nota3title;
    public javax.swing.JLabel nota4content;
    public javax.swing.JLabel nota4title;
    public javax.swing.JLabel nota5content;
    public javax.swing.JLabel nota5title;
    public javax.swing.JLabel tema;
    public javax.swing.JLabel tone;
    // End of variables declaration//GEN-END:variables
}
